language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
install:
  - npm install
  - npm run compile
  - npm prune --production
before_script:
  - node ./bin/graphtype.js -s ./test/github.json -o ./test/github.graphql